/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package au.mebank.finance;

import au.mebank.finance.service.CsvReaderService;
import java.io.File;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.autoconfigure.domain.EntityScan;
import org.springframework.context.annotation.PropertySource;
import org.springframework.data.jpa.repository.config.EnableJpaRepositories;

@EntityScan("au.mebank.finance.model")
@EnableJpaRepositories("au.mebank.finance.repository")
@SpringBootApplication(scanBasePackages = "au.mebank.finance")
@PropertySource(value = { "classpath:application.properties" })
public class Application implements CommandLineRunner {//implements WebApplicationInitializer {

    @Autowired
    private CsvReaderService csvReaderService;

    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }

    @Override
    public void run(String... args) {
        System.out.println("Starting transaction parser application");
        ClassLoader classLoader = getClass().getClassLoader();
        File file = new File(classLoader.getResource("sample.csv").getFile());
        csvReaderService.insertTransaction(file.getAbsolutePath());
    }
}
